application: gaehangson4sinmetal
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 100

handlers:
- url: /queue/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
